options nodate nonumber nonotes nosource;
ods exclude all;
ods graphics off;
data person_x (drop=i);
  length age_grp $20;
  do varstr=1 to 5;
    do varpsu=1 to 3;
   do i=1 to 1000;
           flu=scan('0,1', rantbl(0, .97, .3));
           totexp = 400+rannor(123);
           perwtf=10+ranuni(123);
  if mod(_n_, 2) = 0 then do;
    sex='Female';
    age_grp = '18 years or older';
  end;
  else do;
    sex='Male';
    age_grp = '0-17 years';
  end;
        output;
       end; 
    end; 
  end; 
run;
ods exclude none;
proc contents data=person_x;
run;
